# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/centos-7.2"
  config.vm.provision "shell", path: "./scripts/provision.sh"
  
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false
  config.hostmanager.include_offline = true

  config.cache.scope = :machine
  config.cache.enable :yum

  config.vm.define "server1" do |node|
    node.vm.hostname = 'server1'
    node.vm.network :private_network, ip: '192.168.42.42'
  end

  config.vm.define "server2" do |node|
    node.vm.hostname = 'server2'
    node.vm.network :private_network, ip: '192.168.42.43'
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 2
  end
end
